[env:stm32g070rb]
platform = ststm32
board = nucleo_g070rb
framework = stm32cube


build_flags =
    -I Libraries
    -I Src
    -I Drivers/CMSIS/Include
    -I Drivers/CMSIS/Device/STM32G0xx/Include
    -I Drivers/STM32G0xx_HAL_Driver/Inc
    -Wl,-u,_printf_float
    ; -Wall
    ; -Wextra
    ; -Werror=implicit-function-declaration
    ; -Wformat=2